In [8]:
# download daostack/daos.csv from https://www.kaggle.com/datasets/daviddavo/dao-analyzer

import pandas as pd
df = pd.read_csv('daos.csv')
# drop unnmaed col
df = df.drop(df.columns[0], axis=1)
# add platform = daostack
df['platform'] = 'daostack'
df.head()

,network,id,name,register,nativeToken,nativeReputation,dao,platform
0,mainnet,0x0b93ba560283350d4216f29dc57e15df38d0eace,CuraDAO,registered,0x2d3ca07e3c36b9aeec572a3c625cb45a7a88984a,0xe2c2bbf97599c448aba4561006c8d5929ac08e13,0x0b93ba560283350d4216f29dc57e15df38d0eace,daostack
1,mainnet,0x15344ecdc2c4edfcb092e284d93c20f0529fd8a6,dOrg,registered,0x3b2d0c1b652d5fad3a43f4ada7265371eac050d4,0x53757c07fa372d1ac873c701dccfd1ebcc563e0e,0x15344ecdc2c4edfcb092e284d93c20f0529fd8a6,daostack
2,mainnet,0x273d0f686a53a49a0fba2a801566b19f9aaf8fcd,PrimeDAO,registered,0x40cb13628f087dfcfa6d6c717e9fbf5d5b8bd964,0x4352a94ccb3ea07e16734f66a94e94e474a50b5f,0x273d0f686a53a49a0fba2a801566b19f9aaf8fcd,daostack
3,mainnet,0x294f999356ed03347c7a23bcbcf8d33fa41dc830,Genesis Alpha,registered,0xf88bfeab7217376f33db368a3d3dc11b1433bdfb,0x30412f4c06343d65c06b5a0bba6821cf37e605fa,0x294f999356ed03347c7a23bcbcf8d33fa41dc830,daostack
4,mainnet,0x2b8c70fffda7f3d7667f7cfede1429313886329c,ETHGlobal,registered,0xe5ac9a487f366b6092df1ab59209c4ee4f26236d,0x45413ccd9870c89980dbae9c11315a8a1c1f3f2f,0x2b8c70fffda7f3d7667f7cfede1429313886329c,daostack

In [9]:
# drop network and register
df = df.drop(['network', 'register'], axis=1)
# rename id to platform_id
df = df.rename(columns={'id': 'platform_id'})
df = df[['platform', 'platform_id', 'name']]
df.head()

   platform                                 platform_id           name
0  daostack  0x0b93ba560283350d4216f29dc57e15df38d0eace        CuraDAO
1  daostack  0x15344ecdc2c4edfcb092e284d93c20f0529fd8a6           dOrg
2  daostack  0x273d0f686a53a49a0fba2a801566b19f9aaf8fcd       PrimeDAO
3  daostack  0x294f999356ed03347c7a23bcbcf8d33fa41dc830  Genesis Alpha
4  daostack  0x2b8c70fffda7f3d7667f7cfede1429313886329c      ETHGlobal

In [10]:
# make website and additional columns nans
import numpy as np
df['website'] = np.nan
df['additional'] = np.nan
df.head()

,platform,platform_id,name,website,additional
0,daostack,0x0b93ba560283350d4216f29dc57e15df38d0eace,CuraDAO,NaN,NaN
1,daostack,0x15344ecdc2c4edfcb092e284d93c20f0529fd8a6,dOrg,NaN,NaN
2,daostack,0x273d0f686a53a49a0fba2a801566b19f9aaf8fcd,PrimeDAO,NaN,NaN
3,daostack,0x294f999356ed03347c7a23bcbcf8d33fa41dc830,Genesis Alpha,NaN,NaN
4,daostack,0x2b8c70fffda7f3d7667f7cfede1429313886329c,ETHGlobal,NaN,NaN

In [11]:
# save to csv
df.to_csv('daostack_deployments.csv', index=False)