In [1]:
# open moloches csv into df
import pandas as pd
df = pd.read_csv('moloches.csv')
# drop unnamed column
df = df.drop(df.columns[0], axis=1)
df.head()

,network,id,name,version,summoner,summoningTime,timestamp,proposalCount,memberCount,voteCount,rageQuitCount,totalGas,molochAddress
0,arbitrum,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,Zaibatsu-DAO,2.1,0x8435d0a8f19f748cba91863b70eb986895ee4b49,1662046800,1662046800,2,1,1,0,25655591000000000,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9
1,arbitrum,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a,NaN,2.1,0x399540044cd5fd63bbc6cbec55a14232f65b457b,1652432312,1652432312,0,1,0,0,4446544408757082,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a
2,arbitrum,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,test commando,2.1,0xe3d8c94be1550dbde55811bb39c0d3868bafd068,1667987262,1667987262,1,1,1,1,18888828400000000,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b
3,arbitrum,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8,HIEROPHANT GREEN DAO,2.1,0xbe694be8e812ae1a99443b32041142c36597a772,1651054083,1651054083,0,1,0,0,1473413325719085,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8
4,arbitrum,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85,NaN,2.1,0x0887a7d4ba8ed400f10b651b61ee49afa302c680,1636252707,1636252707,0,1,0,0,25403942773845900,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85

In [2]:
# network val counts
df['network'].value_counts()

xdai        1750
polygon     1118
mainnet      581
arbitrum      80
Name: network, dtype: int64

In [3]:
# version val counts
df['version'].value_counts()

2.1    3241
2.0     136
1.0     108
2.2      44
Name: version, dtype: int64

In [4]:
# platform
# platform_id
# name (may be nan)
# website (may be nan)
# additional (may contain website, social, etc. info, may be nan)
# add column platform
df['platform'] = 'daohaus'
# rename id to platform_id
df = df.rename(columns={'id': 'platform_id'})
# set version col to string
df['version'] = df['version'].astype(str)
# make additional column with network and version
df['additional'] = 'network: ' + df['network'] + ' version: ' + df['version']
df.head()

,network,platform_id,name,version,summoner,summoningTime,timestamp,proposalCount,memberCount,voteCount,rageQuitCount,totalGas,molochAddress,platform,additional
0,arbitrum,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,Zaibatsu-DAO,2.1,0x8435d0a8f19f748cba91863b70eb986895ee4b49,1662046800,1662046800,2,1,1,0,25655591000000000,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,daohaus,network: arbitrum version: 2.1
1,arbitrum,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a,NaN,2.1,0x399540044cd5fd63bbc6cbec55a14232f65b457b,1652432312,1652432312,0,1,0,0,4446544408757082,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a,daohaus,network: arbitrum version: 2.1
2,arbitrum,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,test commando,2.1,0xe3d8c94be1550dbde55811bb39c0d3868bafd068,1667987262,1667987262,1,1,1,1,18888828400000000,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,daohaus,network: arbitrum version: 2.1
3,arbitrum,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8,HIEROPHANT GREEN DAO,2.1,0xbe694be8e812ae1a99443b32041142c36597a772,1651054083,1651054083,0,1,0,0,1473413325719085,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8,daohaus,network: arbitrum version: 2.1
4,arbitrum,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85,NaN,2.1,0x0887a7d4ba8ed400f10b651b61ee49afa302c680,1636252707,1636252707,0,1,0,0,25403942773845900,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85,daohaus,network: arbitrum version: 2.1

In [5]:
# add column website
df['website'] = None
# keep only platform, platform_id, name, website, additional
df = df[['platform', 'platform_id', 'name', 'website', 'additional']]
df

,platform,platform_id,name,website,additional
0,daohaus,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,Zaibatsu-DAO,None,network: arbitrum version: 2.1
1,daohaus,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a,NaN,None,network: arbitrum version: 2.1
2,daohaus,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,test commando,None,network: arbitrum version: 2.1
3,daohaus,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8,HIEROPHANT GREEN DAO,None,network: arbitrum version: 2.1
4,daohaus,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85,NaN,None,network: arbitrum version: 2.1
...,...,...,...,...,...
3524,daohaus,0xff07943f171b826b3618982a6213f157fbc5e226,NaN,None,network: xdai version: 2.1
3525,daohaus,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,array.finance CCO,None,network: xdai version: 2.1
3526,daohaus,0xff4b20d48a1e8f93bf6745de388547e731f96fd0,PRIDEdao,None,network: xdai version: 2.1
3527,daohaus,0xffb676765d521518ac5c0d4f4067a9db9b72901b,EmpanaDAO,None,network: xdai version: 2.0
3528,daohaus,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,Kokonut Network,None,network: xdai version: 2.1

### handle non unique ids

In [6]:
# platform_id val counts
df['platform_id'].value_counts()

0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b    2
0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9    1
0x506b39c021146203c76a1a541f6c952a572331a2    1
0x4dc1a7db6cc1eab1872da7e030c276723a85794c    1
0x4df0e5ea2ed9c4be406b0ae437fce7d31b519270    1
                                             ..
0x77a832095aef23d4a002ddc7c4778dc78498fb05    1
0x77f8d16fc2fabb1e4f6669071228e40734a7db36    1
0x783727194959844111ab37b266ab76aa08e3d2b4    1
0x7953b83aa538c242e56423aa9edef1d9486dafc6    1
0xffe8a8ec2477390c6b97074f44326fac24d7f6dd    1
Name: platform_id, Length: 3528, dtype: int64

In [7]:
# find where platform_id is 0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b
df[df['platform_id'] == '0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b']
combined_additional = df[df['platform_id'] == '0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b']['additional'].values
combined_additional_string = '; '.join(combined_additional)

# replace 0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b additional with combined_additional_string
df.loc[df['platform_id'] == '0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b', 'additional'] = combined_additional_string
df[df['platform_id'] == '0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b']

,platform,platform_id,name,website,additional
650,daohaus,0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b,RealQuickDao,None,network: mainnet version: 2.0; network: xdai v...
3475,daohaus,0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b,RealQuickDao,None,network: mainnet version: 2.0; network: xdai v...

In [8]:
# drop the second instance of 0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b
df = df.drop(df[df['platform_id'] == '0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b'].index[1])
df[df['platform_id'] == '0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b']

,platform,platform_id,name,website,additional
650,daohaus,0xf8484b3d9e8189d4743b0ecf35a87c58b76cee7b,RealQuickDao,None,network: mainnet version: 2.0; network: xdai v...

### add votes count

In [9]:
# read votes csv into df
votes_df = pd.read_csv('votes.csv')
votes_df.head()

,Unnamed: 0,network,id,createdAt,molochAddress,memberAddress,uintVote,proposalAddress
0,0,arbitrum,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9-mem...,1662062323,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,0x8435d0a8f19f748cba91863b70eb986895ee4b49,1,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9-pro...
1,1,arbitrum,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b-mem...,1667995012,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,0xe3d8c94be1550dbde55811bb39c0d3868bafd068,1,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b-pro...
2,2,arbitrum,0x1e5d8415678a99bd69b87df7c2ece3f0c7b2a33a-mem...,1671210654,0x1e5d8415678a99bd69b87df7c2ece3f0c7b2a33a,0xae5de9158a9d0caa66e3f1d931600fa0c27a0911,1,0x1e5d8415678a99bd69b87df7c2ece3f0c7b2a33a-pro...
3,3,arbitrum,0x3a7ebf465d910ecc984872e2316493d5d05ba869-mem...,1675221078,0x3a7ebf465d910ecc984872e2316493d5d05ba869,0x4b933cd816c86783b116d070818c6fcdf5bff17a,1,0x3a7ebf465d910ecc984872e2316493d5d05ba869-pro...
4,4,arbitrum,0x3a7ebf465d910ecc984872e2316493d5d05ba869-mem...,1675006656,0x3a7ebf465d910ecc984872e2316493d5d05ba869,0x78000b0605e81ea9df54b33f72ebc61b5f5c8077,1,0x3a7ebf465d910ecc984872e2316493d5d05ba869-pro...

In [10]:
# keep molochAddress and proposalAddress
votes_df = votes_df[['molochAddress', 'proposalAddress']]
# group by molochAddress and count
votes_df = votes_df.groupby('molochAddress').count()
# flatten
votes_df = votes_df.reset_index()
# rename proposalAddress to votes
votes_df = votes_df.rename(columns={'proposalAddress': 'votes_count'})
votes_df

                                  molochAddress  votes_count
0    0x0042dfb8301607df72ec9fdab39759371f827bb0            5
1    0x0085bf6f179ec9daba8042947be5e161ae9e8087            2
2    0x00aece8e5fbd08b18326e7c4bb3dd77fd693a93f           13
3    0x00cef1af1aa61e7d3802acda7cad25928317a331            1
4    0x014ded81ddb85f7d178a66bcdd6cd6ca89ba7cc5            2
..                                          ...          ...
944  0xfe2d87b14dc0d0d60020b58314b6da197dbab9c6          158
945  0xfe3df41697bd2e4e8afb596857e5f1c0744499b0            5
946  0xfe5dd54317e02dd754b2c0161667f1bd7408de35            1
947  0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d          123
948  0xffe8a8ec2477390c6b97074f44326fac24d7f6dd          266

[949 rows x 2 columns]

In [11]:
# join df and votes_df
df = df.merge(votes_df, how='left', left_on='platform_id', right_on='molochAddress', validate='one_to_one')
df

,platform,platform_id,name,website,additional,molochAddress,votes_count
0,daohaus,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,Zaibatsu-DAO,None,network: arbitrum version: 2.1,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,1.0
1,daohaus,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a,NaN,None,network: arbitrum version: 2.1,NaN,NaN
2,daohaus,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,test commando,None,network: arbitrum version: 2.1,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,1.0
3,daohaus,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8,HIEROPHANT GREEN DAO,None,network: arbitrum version: 2.1,NaN,NaN
4,daohaus,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85,NaN,None,network: arbitrum version: 2.1,NaN,NaN
...,...,...,...,...,...,...,...
3523,daohaus,0xff07943f171b826b3618982a6213f157fbc5e226,NaN,None,network: xdai version: 2.1,NaN,NaN
3524,daohaus,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,array.finance CCO,None,network: xdai version: 2.1,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,123.0
3525,daohaus,0xff4b20d48a1e8f93bf6745de388547e731f96fd0,PRIDEdao,None,network: xdai version: 2.1,NaN,NaN
3526,daohaus,0xffb676765d521518ac5c0d4f4067a9db9b72901b,EmpanaDAO,None,network: xdai version: 2.0,NaN,NaN
3527,daohaus,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,Kokonut Network,None,network: xdai version: 2.1,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,266.0

In [12]:
# how many have votes as nan
df['votes_count'].isna().sum()

2579

In [13]:
# how many have votes
df['votes_count'].notna().sum()

949

In [14]:
# lots of these don't have any votes....
# fill nans with 0
df['votes_count'] = df['votes_count'].fillna(0)
# make this an int
df['votes_count'] = df['votes_count'].astype(int)
df

,platform,platform_id,name,website,additional,molochAddress,votes_count
0,daohaus,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,Zaibatsu-DAO,None,network: arbitrum version: 2.1,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,1
1,daohaus,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a,NaN,None,network: arbitrum version: 2.1,NaN,0
2,daohaus,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,test commando,None,network: arbitrum version: 2.1,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,1
3,daohaus,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8,HIEROPHANT GREEN DAO,None,network: arbitrum version: 2.1,NaN,0
4,daohaus,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85,NaN,None,network: arbitrum version: 2.1,NaN,0
...,...,...,...,...,...,...,...
3523,daohaus,0xff07943f171b826b3618982a6213f157fbc5e226,NaN,None,network: xdai version: 2.1,NaN,0
3524,daohaus,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,array.finance CCO,None,network: xdai version: 2.1,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,123
3525,daohaus,0xff4b20d48a1e8f93bf6745de388547e731f96fd0,PRIDEdao,None,network: xdai version: 2.1,NaN,0
3526,daohaus,0xffb676765d521518ac5c0d4f4067a9db9b72901b,EmpanaDAO,None,network: xdai version: 2.0,NaN,0
3527,daohaus,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,Kokonut Network,None,network: xdai version: 2.1,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,266

### proposals count

In [15]:
proposals_df = pd.read_csv('proposals.csv')
proposals_df.head()

,Unnamed: 0,network,id,createdAt,proposalId,molochAddress,memberAddress,proposer,sponsor,sharesRequested,...,paymentRequested,yesVotes,noVotes,sponsored,sponsoredAt,processed,processedAt,didPass,yesShares,noShares
0,0,arbitrum,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9-pro...,1662047614,0,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,0x8435d0a8f19f748cba91863b70eb986895ee4b49,0x8435d0a8f19f748cba91863b70eb986895ee4b49,0x0000000000000000000000000000000000000000,50,...,0,0,0,False,NaN,False,NaN,False,0,0
1,1,arbitrum,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9-pro...,1662048470,1,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,0x8435d0a8f19f748cba91863b70eb986895ee4b49,0x8435d0a8f19f748cba91863b70eb986895ee4b49,0x8435d0a8f19f748cba91863b70eb986895ee4b49,50,...,0,1,0,True,1.662049e+09,False,NaN,False,1,0
2,2,arbitrum,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b-pro...,1667987888,0,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,0xe3d8c94be1550dbde55811bb39c0d3868bafd068,0xe3d8c94be1550dbde55811bb39c0d3868bafd068,0xe3d8c94be1550dbde55811bb39c0d3868bafd068,0,...,0,1,0,True,1.667988e+09,True,1.669313e+09,True,1,0
3,3,arbitrum,0x15909f6e92e32a6c3187fad2f7ea91f2b3dfdcf9-pro...,1642252357,0,0x15909f6e92e32a6c3187fad2f7ea91f2b3dfdcf9,0x54c375c481f95ba43e2cecd6ef30631f55518f57,0x54c375c481f95ba43e2cecd6ef30631f55518f57,0x0000000000000000000000000000000000000000,0,...,0,0,0,False,NaN,False,NaN,False,0,0
4,4,arbitrum,0x15909f6e92e32a6c3187fad2f7ea91f2b3dfdcf9-pro...,1642252710,1,0x15909f6e92e32a6c3187fad2f7ea91f2b3dfdcf9,0x54c375c481f95ba43e2cecd6ef30631f55518f57,0x54c375c481f95ba43e2cecd6ef30631f55518f57,0x0000000000000000000000000000000000000000,1,...,0,0,0,False,NaN,False,NaN,False,0,0

In [16]:
# keep id and molochAddress
proposals_df = proposals_df[['id', 'molochAddress']]
# group by molochAddress and count
proposals_df = proposals_df.groupby('molochAddress').count()
# flatten
proposals_df = proposals_df.reset_index()
# rename id to proposals_count
proposals_df = proposals_df.rename(columns={'id': 'proposals_count'})
proposals_df

                                   molochAddress  proposals_count
0     0x00318178cc9ccd3be185de3cf194d374d72b084b                2
1     0x0042dfb8301607df72ec9fdab39759371f827bb0                6
2     0x005aab335988cdfce02b22157b5dd152440cf95d                1
3     0x0066a5b03aa808a23e9b19a5e09e3e11ef02b290                1
4     0x0085bf6f179ec9daba8042947be5e161ae9e8087                2
...                                          ...              ...
1452  0xffb2a16b050b76c37d14dbb1475bfbf6386cdaf4                2
1453  0xffb676765d521518ac5c0d4f4067a9db9b72901b                3
1454  0xffb8ab9a84b900e6a689146dc11579cb2342e4ab                2
1455  0xffe8a8ec2477390c6b97074f44326fac24d7f6dd               90
1456  0xffeb5446529e643664f90343e1b25ecb36362784                2

[1457 rows x 2 columns]

In [17]:
# merge df and proposals_df
df = df.merge(proposals_df, how='left', left_on='platform_id', right_on='molochAddress', validate='one_to_one')
df

,platform,platform_id,name,website,additional,molochAddress_x,votes_count,molochAddress_y,proposals_count
0,daohaus,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,Zaibatsu-DAO,None,network: arbitrum version: 2.1,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,1,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,2.0
1,daohaus,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a,NaN,None,network: arbitrum version: 2.1,NaN,0,NaN,NaN
2,daohaus,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,test commando,None,network: arbitrum version: 2.1,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,1,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,1.0
3,daohaus,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8,HIEROPHANT GREEN DAO,None,network: arbitrum version: 2.1,NaN,0,NaN,NaN
4,daohaus,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85,NaN,None,network: arbitrum version: 2.1,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3523,daohaus,0xff07943f171b826b3618982a6213f157fbc5e226,NaN,None,network: xdai version: 2.1,NaN,0,NaN,NaN
3524,daohaus,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,array.finance CCO,None,network: xdai version: 2.1,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,123,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,122.0
3525,daohaus,0xff4b20d48a1e8f93bf6745de388547e731f96fd0,PRIDEdao,None,network: xdai version: 2.1,NaN,0,NaN,NaN
3526,daohaus,0xffb676765d521518ac5c0d4f4067a9db9b72901b,EmpanaDAO,None,network: xdai version: 2.0,NaN,0,0xffb676765d521518ac5c0d4f4067a9db9b72901b,3.0
3527,daohaus,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,Kokonut Network,None,network: xdai version: 2.1,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,266,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,90.0

In [18]:
# count of proposals_count nans
df['proposals_count'].isna().sum()

2071

In [19]:
# count not nans
df['proposals_count'].notna().sum()

1457

In [20]:
df['proposals_count'] = df['proposals_count'].fillna(0)
df

,platform,platform_id,name,website,additional,molochAddress_x,votes_count,molochAddress_y,proposals_count
0,daohaus,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,Zaibatsu-DAO,None,network: arbitrum version: 2.1,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,1,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,2.0
1,daohaus,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a,NaN,None,network: arbitrum version: 2.1,NaN,0,NaN,0.0
2,daohaus,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,test commando,None,network: arbitrum version: 2.1,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,1,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,1.0
3,daohaus,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8,HIEROPHANT GREEN DAO,None,network: arbitrum version: 2.1,NaN,0,NaN,0.0
4,daohaus,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85,NaN,None,network: arbitrum version: 2.1,NaN,0,NaN,0.0
...,...,...,...,...,...,...,...,...,...
3523,daohaus,0xff07943f171b826b3618982a6213f157fbc5e226,NaN,None,network: xdai version: 2.1,NaN,0,NaN,0.0
3524,daohaus,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,array.finance CCO,None,network: xdai version: 2.1,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,123,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,122.0
3525,daohaus,0xff4b20d48a1e8f93bf6745de388547e731f96fd0,PRIDEdao,None,network: xdai version: 2.1,NaN,0,NaN,0.0
3526,daohaus,0xffb676765d521518ac5c0d4f4067a9db9b72901b,EmpanaDAO,None,network: xdai version: 2.0,NaN,0,0xffb676765d521518ac5c0d4f4067a9db9b72901b,3.0
3527,daohaus,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,Kokonut Network,None,network: xdai version: 2.1,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,266,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,90.0

In [21]:
# make column an int
df['proposals_count'] = df['proposals_count'].astype(int)
# drop molochAddress_x and molochAddress_y
df = df.drop(columns=['molochAddress_x', 'molochAddress_y'])
df

,platform,platform_id,name,website,additional,votes_count,proposals_count
0,daohaus,0x02c6c33b9bb6b2fc8ae9ab43a0235f4d7897b5d9,Zaibatsu-DAO,None,network: arbitrum version: 2.1,1,2
1,daohaus,0x0a96234adacd1e71c9b2a237cf12374f64e05e3a,NaN,None,network: arbitrum version: 2.1,0,0
2,daohaus,0x0d8d5002562405cb1ed598ff4fb48c948f36a18b,test commando,None,network: arbitrum version: 2.1,1,1
3,daohaus,0x0feb2ee31f9d8bcc580f18d4fe8ed9de61d02ff8,HIEROPHANT GREEN DAO,None,network: arbitrum version: 2.1,0,0
4,daohaus,0x1543bcdf759c0fccbb375a8b8b0c5fd1393a9b85,NaN,None,network: arbitrum version: 2.1,0,0
...,...,...,...,...,...,...,...
3523,daohaus,0xff07943f171b826b3618982a6213f157fbc5e226,NaN,None,network: xdai version: 2.1,0,0
3524,daohaus,0xff3f8c0b98454306fb0bda57e5ae38cbfa66cc0d,array.finance CCO,None,network: xdai version: 2.1,123,122
3525,daohaus,0xff4b20d48a1e8f93bf6745de388547e731f96fd0,PRIDEdao,None,network: xdai version: 2.1,0,0
3526,daohaus,0xffb676765d521518ac5c0d4f4067a9db9b72901b,EmpanaDAO,None,network: xdai version: 2.0,0,3
3527,daohaus,0xffe8a8ec2477390c6b97074f44326fac24d7f6dd,Kokonut Network,None,network: xdai version: 2.1,266,90

In [22]:
# save as dao_deployments.csv
df.to_csv('daohaus_deployments.csv', index=False)