In [1]:
import requests

response = requests.get('https://www.tally.xyz/api/search-daos')

import pandas as pd
df = pd.DataFrame(response.json()['governances'])
df.head()

,id,slug,name,kind,chainId,organization
0,eip155:10:0x8087dE46076212A21EA5cD8b4368BCbd82...,sector-3-optimism,Sector#3 (Optimism),SINGLE_GOV,eip155:10,"{'name': 'Sector#3 (Optimism)', 'slug': 'secto..."
1,eip155:137:0x3343aEb44A2a277e3Ae346014e181aE15...,coindaox,CoinDaoX,SINGLE_GOV,eip155:137,"{'name': 'CoinDaoX', 'slug': 'coindaox', 'visu..."
2,eip155:1:0x064515Cc2dcf070b6302d2B9ffc9643c449...,tai,TAI Governance,SINGLE_GOV,eip155:1,"{'name': 'TAI Governance', 'slug': 'tai-govern..."
3,eip155:100:0x96853087C9E364FE9554fD6FCFE13BcD9...,spore-engineering,Spore Engineering,SINGLE_GOV,eip155:100,"{'name': 'Spore Engineering', 'slug': 'dsfsdf'..."
4,eip155:1:0xFb6B7C11a55C57767643F1FF65c34C8693a...,diva,Diva Staking,SINGLE_GOV,eip155:1,"{'name': 'Diva Staking', 'slug': 'diva-staking..."

In [2]:
df.columns

Index(['id', 'slug', 'name', 'kind', 'chainId', 'organization'], dtype='object')

In [3]:
# drop columns chainId, visual, and governances
df = df.drop(columns=['chainId', 'kind', 'organization'])
df.head()

,id,slug,name
0,eip155:10:0x8087dE46076212A21EA5cD8b4368BCbd82...,sector-3-optimism,Sector#3 (Optimism)
1,eip155:137:0x3343aEb44A2a277e3Ae346014e181aE15...,coindaox,CoinDaoX
2,eip155:1:0x064515Cc2dcf070b6302d2B9ffc9643c449...,tai,TAI Governance
3,eip155:100:0x96853087C9E364FE9554fD6FCFE13BcD9...,spore-engineering,Spore Engineering
4,eip155:1:0xFb6B7C11a55C57767643F1FF65c34C8693a...,diva,Diva Staking

In [4]:
# add platform column
df['platform'] = 'tally'
df = df.rename(columns={'id': 'platform_id'})
df

,platform_id,slug,name,platform
0,eip155:10:0x8087dE46076212A21EA5cD8b4368BCbd82...,sector-3-optimism,Sector#3 (Optimism),tally
1,eip155:137:0x3343aEb44A2a277e3Ae346014e181aE15...,coindaox,CoinDaoX,tally
2,eip155:1:0x064515Cc2dcf070b6302d2B9ffc9643c449...,tai,TAI Governance,tally
3,eip155:100:0x96853087C9E364FE9554fD6FCFE13BcD9...,spore-engineering,Spore Engineering,tally
4,eip155:1:0xFb6B7C11a55C57767643F1FF65c34C8693a...,diva,Diva Staking,tally
...,...,...,...,...
574,eip155:1:0x0BEF27FEB58e857046d630B2c03dFb7bae5...,fei,Fei,tally
575,eip155:137:0x9B3a9e3f289095A7E1117deb3bD29Fd7C...,under3,Under3,tally
576,eip155:137:0x89de859404FeAC5346f5a843Db6B5E136...,harry-potter-82,Harry Potter,tally
577,eip155:137:0x806713eAAAAFEBfb4F0f6d6ED54775f76...,allturn-space-83,AllTurn.Space,tally
578,eip155:137:0x010C5507C43a161240d4C0FA40043244c...,immunity-dao-181,Immunity DAO,tally

In [5]:
# make website column from https://www.tally.xyz/gov/<platform_id>
df['website'] = 'https://www.tally.xyz/gov/' + df['platform_id']
df

,platform_id,slug,name,platform,website
0,eip155:10:0x8087dE46076212A21EA5cD8b4368BCbd82...,sector-3-optimism,Sector#3 (Optimism),tally,https://www.tally.xyz/gov/eip155:10:0x8087dE46...
1,eip155:137:0x3343aEb44A2a277e3Ae346014e181aE15...,coindaox,CoinDaoX,tally,https://www.tally.xyz/gov/eip155:137:0x3343aEb...
2,eip155:1:0x064515Cc2dcf070b6302d2B9ffc9643c449...,tai,TAI Governance,tally,https://www.tally.xyz/gov/eip155:1:0x064515Cc2...
3,eip155:100:0x96853087C9E364FE9554fD6FCFE13BcD9...,spore-engineering,Spore Engineering,tally,https://www.tally.xyz/gov/eip155:100:0x9685308...
4,eip155:1:0xFb6B7C11a55C57767643F1FF65c34C8693a...,diva,Diva Staking,tally,https://www.tally.xyz/gov/eip155:1:0xFb6B7C11a...
...,...,...,...,...,...
574,eip155:1:0x0BEF27FEB58e857046d630B2c03dFb7bae5...,fei,Fei,tally,https://www.tally.xyz/gov/eip155:1:0x0BEF27FEB...
575,eip155:137:0x9B3a9e3f289095A7E1117deb3bD29Fd7C...,under3,Under3,tally,https://www.tally.xyz/gov/eip155:137:0x9B3a9e3...
576,eip155:137:0x89de859404FeAC5346f5a843Db6B5E136...,harry-potter-82,Harry Potter,tally,https://www.tally.xyz/gov/eip155:137:0x89de859...
577,eip155:137:0x806713eAAAAFEBfb4F0f6d6ED54775f76...,allturn-space-83,AllTurn.Space,tally,https://www.tally.xyz/gov/eip155:137:0x806713e...
578,eip155:137:0x010C5507C43a161240d4C0FA40043244c...,immunity-dao-181,Immunity DAO,tally,https://www.tally.xyz/gov/eip155:137:0x010C550...

In [6]:
# add an empty additional column
df['additional'] = None
df = df[['platform', 'platform_id', 'name', 'additional', 'website']]
df

,platform,platform_id,name,additional,website
0,tally,eip155:10:0x8087dE46076212A21EA5cD8b4368BCbd82...,Sector#3 (Optimism),None,https://www.tally.xyz/gov/eip155:10:0x8087dE46...
1,tally,eip155:137:0x3343aEb44A2a277e3Ae346014e181aE15...,CoinDaoX,None,https://www.tally.xyz/gov/eip155:137:0x3343aEb...
2,tally,eip155:1:0x064515Cc2dcf070b6302d2B9ffc9643c449...,TAI Governance,None,https://www.tally.xyz/gov/eip155:1:0x064515Cc2...
3,tally,eip155:100:0x96853087C9E364FE9554fD6FCFE13BcD9...,Spore Engineering,None,https://www.tally.xyz/gov/eip155:100:0x9685308...
4,tally,eip155:1:0xFb6B7C11a55C57767643F1FF65c34C8693a...,Diva Staking,None,https://www.tally.xyz/gov/eip155:1:0xFb6B7C11a...
...,...,...,...,...,...
574,tally,eip155:1:0x0BEF27FEB58e857046d630B2c03dFb7bae5...,Fei,None,https://www.tally.xyz/gov/eip155:1:0x0BEF27FEB...
575,tally,eip155:137:0x9B3a9e3f289095A7E1117deb3bD29Fd7C...,Under3,None,https://www.tally.xyz/gov/eip155:137:0x9B3a9e3...
576,tally,eip155:137:0x89de859404FeAC5346f5a843Db6B5E136...,Harry Potter,None,https://www.tally.xyz/gov/eip155:137:0x89de859...
577,tally,eip155:137:0x806713eAAAAFEBfb4F0f6d6ED54775f76...,AllTurn.Space,None,https://www.tally.xyz/gov/eip155:137:0x806713e...
578,tally,eip155:137:0x010C5507C43a161240d4C0FA40043244c...,Immunity DAO,None,https://www.tally.xyz/gov/eip155:137:0x010C550...

In [7]:
# save
df.to_csv('tally_deployments.csv', index=False)